Working prototype for the demo
ai-cfia/fertiscan-backend pull request #13
Opened 2024-05-21 17:44 UTC by snakedye

* https://github.com/ai-cfia/fertiscan-backend/issues/11
* https://github.com/ai-cfia/fertiscan-backend/issues/12
* Closes https://github.com/ai-cfia/fertiscan-backend/issues/8
* Closes https://github.com/ai-cfia/fertiscan-backend/issues/7
* Closes https://github.com/ai-cfia/fertiscan-backend/issues/9

Once this PR is merged it should serve as the reference for building the front-end.

2024-05-21 18:37 UTC, ibrahim-kabir requested changes
**Checks (workflows) are not working** ❌
Add checks for markdown
README.md is empty, add **at least** the setup procedure for development and explanation about this repo.

2024-05-21 18:37 UTC, ibrahim-kabir commented on app.py
> +from backend import DocumentStore, OCR, LanguageModel
Import orders 👆🏻

2024-05-21 18:37 UTC, ibrahim-kabir commented on app.py
> +UPLOAD_FOLDER = 'uploads'
Should be an environment variable

2024-05-21 18:37 UTC, ibrahim-kabir commented on backend/document_store.py
> +class DocumentStore:
Bad naming, DocumentStore refers to a market.
```suggest
class DocumentStorage:
```

2024-05-21 18:37 UTC, ibrahim-kabir commented on backend/document_store.py
> +            raise ValueError("The document must be a file path (str) or in bytes format.")
Nice, error handling 👍 !

2024-05-21 18:37 UTC, ibrahim-kabir commented on backend/document_store.py
> +            file.close()
Try/Except would be more suited in this case.
> You should do what you expect to work. If it doesn’t work and an exception happens, then just catch the exception and handle it appropriately.
[Source](https://realpython.com/python-lbyl-vs-eafp/#:~:text=The%20%E2%80%9CEasier%20to%20Ask%20Forgiveness%20Than%20Permission%E2%80%9D%20(EAFP)%20Style,-Grace%20Murray%20Hopper&text=It%20suggests%20that%20right%20away,exception%20and%20handle%20it%20appropriately.&text=In%20Python%2C%20the%20EAFP%20coding%20style%20is%20pretty%20popular%20and%20common.)

2024-05-21 18:37 UTC, ibrahim-kabir commented on backend/language_model.py
> +prompt_file = open('./prompt.txt')
prompt.txt should be an environment variable. Such as "PROMPT_PATH"

2024-05-21 18:37 UTC, ibrahim-kabir commented on backend/language_model.py
> +prompt_file.close()
Why are you doing this ? Whis isn't this into the class ?

2024-05-21 18:37 UTC, ibrahim-kabir commented on requirements.txt
> +openai
Add a newline

2024-05-21 18:37 UTC, ibrahim-kabir commented on tests/test_document_store.py
> +from backend import DocumentStore  # Replace 'your_module_path' with the actual module path
Order imports

2024-05-22 13:40 UTC, SamuelPelletierEvraire approved these changes
All good, just make the request that ibrahim ask

2024-05-22 13:42 UTC, SamuelPelletierEvraire commented
For the workflow, we are going to fix this after the demo because we don't have time for now

2024-05-22 13:49 UTC, merged