Implement End-to-End Testing for Image-to-Form Processing Pipeline
ai-cfia/fertiscan-backend pull request #58
Opened 2024-06-10 22:32 UTC by Endlessflow

### Pull Request: Implement End-to-End Testing for Image-to-Form Processing Pipeline

#### Description:
This PR introduces a comprehensive end-to-end testing script for our image-to-form processing pipeline. The aim is to ensure the pipeline’s reliability and performance by facilitating seamless testing across various components, including OCR engines and LLM models.

#### Key Changes:
1. **End-to-End Testing Script (`e2e.py`)**:
   - **Pipeline Processing**: Developed a script to process input images through all combinations of OCR engines and LLM models.
   - **Directory Structure**: Established a structured directory setup under `e2e_tests` for input images, and outputs from OCR and LLM processes.
   - **Output Management**: Implemented checks to skip processing if output files already exist, optimizing the testing process and preventing redundant operations.
   - **Environment Management**: Improved handling of environment variables and enhanced logging for better configuration validation and error tracking.
   - **Error Handling**: Added detailed logging and error handling to provide insights during the processing flow.

2. **GPT Class Enhancements (`backend/gpt.py`)**:
   - **Debug Logging**: Added optional debug logging to track the timing and details of AzureOpenAI requests, aiding in performance monitoring.
   - **Request Parameter Handling**: Refactored the `GPT` class to improve parameter handling in an attempt to support models with varying feature availability, enhancing compatibility.
   
*Closes issue #45*

2024-06-10 22:37 UTC, Endlessflow commented
@snakedye this is a draft mainly because I am not sure if `e2e.py` should stay in the root and if not where to put it. 

Otherwise, everything else is working and ready (except maybe Ollama support that needs to be discussed).

2024-06-11 13:36 UTC, snakedye requested changes
GG, there's only this minor issue left.

2024-06-11 13:36 UTC, snakedye commented on backend/gpt.py
> +        if DEBUG:
Everything under the `DEBUG` flag should go in the test file (./e2e.py)

2024-06-11 13:36 UTC, snakedye commented on backend/gpt.py
> +        models_with_response_format = ["ailab-llm"] # List of models that support the response_format option
Set it as a constant at the beginning of the file.
```
MODELS_WITH_RESPONSE_FORMAT = ["ailab-llm"]
```

2024-06-11 13:36 UTC, snakedye commented on backend/gpt.py
> +        if DEBUG:
Move to the test file.

2024-06-11 13:36 UTC, snakedye commented on e2e.py
Find a more descriptive name for the file.

* test_e2e_pipeline.py
* generate_e2e_results.py

2024-06-11 13:36 UTC, snakedye commented on backend/gpt.py
> +    def generate_form(self, prompt, DEBUG=False):
Remove the `DEBUG` flag.

2024-06-12 13:09 UTC, snakedye commented
Don't forget to pass the checks 2 to 5. For the tests post a screenshot of the result of the test suite. Unfortunately the pipeline isn't fixed yet.

2024-06-20 20:03 UTC, Endlessflow commented
Alright, it appears that everything is functioning as expected locally. Proceeding with the merge seems like a reasonable next step.

![image](https://github.com/ai-cfia/fertiscan-backend/assets/60270865/6ccabd22-57b7-49c6-9b7f-b81bc350e350)

2024-06-20 20:04 UTC, snakedye approved these changes

2024-06-20 20:04 UTC, merged