Change the nutrient format
ai-cfia/fertiscan-backend pull request #79
Opened 2024-07-02 18:11 UTC by snakedye

Close #78

2024-07-02 18:54 UTC, Francois-Werbrouck commented on tests/test_form.py
> +        self.assertEqual(form.company_name, "ABC Company")
Take a look at https://github.com/ai-cfia/nachet-datastore/blob/9278eda4a03d5256dcbd3d64646c44dbdca75b6e/tests/test_metadata.py#L63 This should make your testing less redundant 😉

2024-07-02 18:58 UTC, Francois-Werbrouck commented on tests/test_form.py
> +        with self.assertRaises(ValidationError):
Shouldn't this be a module defined type of error instead of a generic ValidationError?

2024-07-02 19:00 UTC, Francois-Werbrouck requested changes

2024-07-02 19:00 UTC, Francois-Werbrouck commented on tests/test_form.py
> +        with self.assertRaises(ValidationError):
Shouldn't this be a module defined type of error instead of a generic ValidationError?

2024-07-03 17:31 UTC, Francois-Werbrouck approved these changes
Having error built in your modules will help future and other devs to maintain the tool (it could be an issue of its own). It also is a way to specifically test for this error type in your test suite. Other than that LGTM!

2024-07-03 17:31 UTC, Francois-Werbrouck commented on backend/form.py
```python
class npkError(ValueError):
pass
```

2024-07-03 17:31 UTC, Francois-Werbrouck commented on backend/form.py
> +                raise ValueError('npk must be in the format "number-number-number"')
```python
raise npkError('npk must be in the format "number-number-number"')
```

2024-07-04 14:12 UTC, Youllou approved these changes

2024-07-04 14:40 UTC, merged